# Generated by Django 5.2 on 2025-04-19 05:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendapp', '0002_remove_gym_close_time_remove_gym_open_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boxer',
            name='join_date',
        ),
        migrations.RemoveField(
            model_name='gym',
            name='is_active',
        ),
        migrations.AddField(
            model_name='boxer',
            name='gym_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='boxers', to='backendapp.gym'),
        ),
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('gym_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coaches', to='backendapp.gym')),
            ],
        ),
        migrations.CreateModel(
            name='Fight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opponent_name', models.CharField(max_length=255)),
                ('event_name', models.CharField(max_length=255)),
                ('fight_date', models.DateField()),
                ('location', models.CharField(max_length=255)),
                ('result', models.CharField(choices=[('win', 'Win'), ('loss', 'Loss'), ('draw', 'Draw'), ('nc', 'No Contest')], max_length=10)),
                ('method', models.CharField(choices=[('KO', 'ko'), ('TKO', 'tko'), ('UD', 'ud'), ('SD', 'sd')], max_length=100)),
                ('rounds', models.PositiveIntegerField()),
                ('boxer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fights', to='backendapp.boxer')),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('duration_minutes', models.PositiveIntegerField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('boxer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='backendapp.boxer')),
                ('coach_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='backendapp.coach')),
            ],
        ),
    ]
