# Generated by Django 5.2 on 2025-04-22 18:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendapp', '0003_remove_boxer_join_date_remove_gym_is_active_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SparringReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('gym', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='backendapp.gym')),
                ('opponent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sparring_invites', to='backendapp.boxer')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sparring_requests', to='backendapp.boxer')),
            ],
        ),
    ]
